export const ICY_CONTRACT_ADDRESS = process.env
  .NEXT_PUBLIC_ICY_CONTRACT_ADDRESS as `0x${string}`;
export const ICY_SWAPPER_CONTRACT_ADDRESS = process.env
  .NEXT_PUBLIC_ICY_SWAPPER_CONTRACT_ADDRESS as `0x${string}`;
export const USDC_CONTRACT_ADDRESS =
  "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174";
